
intervalos:
    - 'Menos de 8'
    - '8 a 9'
    - '10 a 12'
    - '13 a 14'
    - '15 a 16'
    - '17 a 18'
    - '19  y más'

bloques:
    hurtos_robos:
        - 'Hurto de dinero a personas conocidas'
        - 'Hurto de dinero a desconocidos'
        - 'Hurto de pertenencias a personas conocidas'
        - 'Hurto de pertenencias a desconocidos'
        - 'Hurto de artículos en la escuela o trabajo'
        - 'Hurto de artículos de supermercados'
        - 'Hurto de artículos de tiendas'
        - 'Robo de carteras o billeteras'
        - 'Robo de celulares o MP3'
        - 'Robo de joyas'
        - 'Robo de notebooks'
        - 'Robo de cartera en auto detenido en semaforo o taco'
        - 'Robo de vehículos motorizados'
        - 'Robo de partes de vehículos'
        - 'Robo de objetos del interior de vehículos'
        - 'Robo de dinero o especies desde máquinas'
        - 'Robo de cables de tendido público'
        - 'Robo de bodegas comerciales'
        - 'Robo en negocios cuando están cerrados'
        - 'Robo de bancos, casinos o cajeros automáticos'
        - 'Robo de kioskos'
        - 'Robo en casas de veraneo fuera de temporada'
        - 'Robo en casas particulares'
        - 'Robo en departamentos'
        - 'Robo en casas rodantes o camping'
        - 'Asalto a personas en la vía pública'
        - 'Asalto a personas en sus domicilios'
        - 'Asalto a choferes de transporte público'
        - 'Asalto a bencineras'
        - 'Asalto a negocios'
        - 'Otros'
    agresiones:
        - 'Participación en riñas o peleas'
        - 'Lesiones leves'
        - 'Lesiones graves'
        - 'Lesiones gravísimas o amputación'
        - 'Homicidio simple'
        - 'Cuasidelito de homicidio'
        - 'Homicidio calificado'
        - 'Parricidio'
        - 'Abuso sexual de menor de 14 años'
        - 'Abuso sexual de mayor de 14 años'
        - 'Violación de menor de 14 años'
        - 'Violación de mayor de 14 años'
        - 'Otros'
    otros_delitos:
        - 'Alteración del orden público  por efecto del alcohol'
        - 'Conducción bajo efecto del alcohol'
        - 'Venta clandestina de alcohol'
        - 'Cultivo o cosecha de drogas'
        - 'Microtráfico  de drogas '
        - 'Asociación ilícita para narcotráfico'
        - 'Elaboración o producción de drogas o alcohol'
        - 'Incendio'
        - 'Vandalismo o desórdenes públicos'
        - 'Reproducción o venta de artículos piratas (música, películas, programas u otros)'
        - 'Receptación'
        - 'Abigeato'
        - 'Secuestro'
        - 'Terrorismo'
        - 'Realización o inducción al aborto'
        - 'Violencia Intrafamiliar o de pareja'
        - 'Exhibicionismo o relaciones sexuales en público'
        - 'Inducción a la prostitución'
        - 'Otros'
    preguntas:
        opciones:
            - 'Yo me identifico',
            - 'Mis amigos me dicen'
        items:
            - 'Chorizo Hampón'
            - 'Choro Vivo'
            - 'Picao Choro'
            - 'Soldado'
            - 'Doméstico'
            - 'Cocodrilo'
            - 'Pollo'
            - 'Perkin'
            - 'Pico Hueso (Violeta o Sohue)'
            - 'Monrrero'
            - 'Cogotero'
            - 'Mechero'
            - 'Lanza'
            - 'Cuatrero'
            - 'Asesino'
            - 'Ninguno'
            - 'Otro'
