<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Instrumento', 'doctrine');

/**
 * BaseInstrumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $titulo
 * @property string $descripcion
 * @property Doctrine_Collection $SeccionInstrumento
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method string              getTitulo()             Returns the current record's "titulo" value
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method Doctrine_Collection getSeccionInstrumento() Returns the current record's "SeccionInstrumento" collection
 * @method Instrumento         setId()                 Sets the current record's "id" value
 * @method Instrumento         setNombre()             Sets the current record's "nombre" value
 * @method Instrumento         setTitulo()             Sets the current record's "titulo" value
 * @method Instrumento         setDescripcion()        Sets the current record's "descripcion" value
 * @method Instrumento         setSeccionInstrumento() Sets the current record's "SeccionInstrumento" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstrumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('instrumento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('titulo', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('descripcion', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 300,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SeccionInstrumento', array(
             'local' => 'id',
             'foreign' => 'instrumento_id'));
    }
}