<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IrncRespuestasFixedComxbloque', 'doctrine');

/**
 * BaseIrncRespuestasFixedComxbloque
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property string $comentario
 * @property integer $id_encuestado
 * @property integer $bloque_irnc
 * 
 * @method integer                       getIdUser()        Returns the current record's "id_user" value
 * @method string                        getComentario()    Returns the current record's "comentario" value
 * @method integer                       getIdEncuestado()  Returns the current record's "id_encuestado" value
 * @method integer                       getBloqueIrnc()    Returns the current record's "bloque_irnc" value
 * @method IrncRespuestasFixedComxbloque setIdUser()        Sets the current record's "id_user" value
 * @method IrncRespuestasFixedComxbloque setComentario()    Sets the current record's "comentario" value
 * @method IrncRespuestasFixedComxbloque setIdEncuestado()  Sets the current record's "id_encuestado" value
 * @method IrncRespuestasFixedComxbloque setBloqueIrnc()    Sets the current record's "bloque_irnc" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIrncRespuestasFixedComxbloque extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('irnc_respuestas_fixed_comxbloque');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('comentario', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('bloque_irnc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}