<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Encuestado', 'doctrine');

/**
 * BaseEncuestado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_encuestado
 * @property integer $id_user_responsable_principal
 * @property integer $select_user_responsable_secundario1
 * @property integer $id_user_responsable_secundario
 * @property string $input_run_nconverificador
 * @property string $input_primer_nombre
 * @property string $input_otros_nombres
 * @property string $input_primer_apellido
 * @property string $input_segundo_apellido
 * @property string $radio_sexo
 * @property timestamp $input_fnacimiento
 * @property string $select_region
 * @property string $select_provincia
 * @property string $select_comuna
 * @property string $radio_procedencia
 * @property string $input_localidad_indigena
 * @property string $select_origen_etnico
 * @property string $select_ingreso_familiar
 * @property string $select_residencia_regular
 * @property string $select_hijo
 * @property string $select_ultimcurso_aprobado
 * @property string $input_anio_ultimocurso
 * @property string $select_actesc_encurso
 * @property string $select_tipo_asistencia
 * @property string $select_asistencia_pconace
 * @property string $select_tipo_pconace
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property string $select_nacionalidad
 * @property string $input_domicilio
 * @property SfGuardUser $SfGuardUser
 * @property SfGuardUser $SfGuardUser_2
 * @property Doctrine_Collection $Cacsa2Respuestas
 * @property Doctrine_Collection $Cacsa3Respuestas
 * @property Doctrine_Collection $CaieRespuestas
 * @property Doctrine_Collection $CsveRespuestas
 * @property Doctrine_Collection $DepAdoRespuestas
 * @property Doctrine_Collection $EgedRespuestas
 * @property Doctrine_Collection $EncuestadoActinputado
 * @property Doctrine_Collection $EncuestadoCanteriores
 * @property Doctrine_Collection $EncuestadoSanciones
 * @property Doctrine_Collection $EstadosInstrumentos
 * @property Doctrine_Collection $FerrRespuestas
 * @property Doctrine_Collection $IrncRespuestas
 * @property Doctrine_Collection $IrncRespuestas_4
 * @property Doctrine_Collection $JirRespuestas
 * @property Doctrine_Collection $MaciRespuestas
 * @property Doctrine_Collection $SqifaRespuestas
 * 
 * @method integer             getIdEncuestado()                        Returns the current record's "id_encuestado" value
 * @method integer             getIdUserResponsablePrincipal()          Returns the current record's "id_user_responsable_principal" value
 * @method integer             getSelectUserResponsableSecundario1()    Returns the current record's "select_user_responsable_secundario1" value
 * @method integer             getIdUserResponsableSecundario()         Returns the current record's "id_user_responsable_secundario" value
 * @method string              getInputRunNconverificador()             Returns the current record's "input_run_nconverificador" value
 * @method string              getInputPrimerNombre()                   Returns the current record's "input_primer_nombre" value
 * @method string              getInputOtrosNombres()                   Returns the current record's "input_otros_nombres" value
 * @method string              getInputPrimerApellido()                 Returns the current record's "input_primer_apellido" value
 * @method string              getInputSegundoApellido()                Returns the current record's "input_segundo_apellido" value
 * @method string              getRadioSexo()                           Returns the current record's "radio_sexo" value
 * @method timestamp           getInputFnacimiento()                    Returns the current record's "input_fnacimiento" value
 * @method string              getSelectRegion()                        Returns the current record's "select_region" value
 * @method string              getSelectProvincia()                     Returns the current record's "select_provincia" value
 * @method string              getSelectComuna()                        Returns the current record's "select_comuna" value
 * @method string              getRadioProcedencia()                    Returns the current record's "radio_procedencia" value
 * @method string              getInputLocalidadIndigena()              Returns the current record's "input_localidad_indigena" value
 * @method string              getSelectOrigenEtnico()                  Returns the current record's "select_origen_etnico" value
 * @method string              getSelectIngresoFamiliar()               Returns the current record's "select_ingreso_familiar" value
 * @method string              getSelectResidenciaRegular()             Returns the current record's "select_residencia_regular" value
 * @method string              getSelectHijo()                          Returns the current record's "select_hijo" value
 * @method string              getSelectUltimcursoAprobado()            Returns the current record's "select_ultimcurso_aprobado" value
 * @method string              getInputAnioUltimocurso()                Returns the current record's "input_anio_ultimocurso" value
 * @method string              getSelectActescEncurso()                 Returns the current record's "select_actesc_encurso" value
 * @method string              getSelectTipoAsistencia()                Returns the current record's "select_tipo_asistencia" value
 * @method string              getSelectAsistenciaPconace()             Returns the current record's "select_asistencia_pconace" value
 * @method string              getSelectTipoPconace()                   Returns the current record's "select_tipo_pconace" value
 * @method timestamp           getCreatedAt()                           Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                           Returns the current record's "updated_at" value
 * @method string              getSelectNacionalidad()                  Returns the current record's "select_nacionalidad" value
 * @method string              getInputDomicilio()                      Returns the current record's "input_domicilio" value
 * @method SfGuardUser         getSfGuardUser()                         Returns the current record's "SfGuardUser" value
 * @method SfGuardUser         getSfGuardUser2()                        Returns the current record's "SfGuardUser_2" value
 * @method Doctrine_Collection getCacsa2Respuestas()                    Returns the current record's "Cacsa2Respuestas" collection
 * @method Doctrine_Collection getCacsa3Respuestas()                    Returns the current record's "Cacsa3Respuestas" collection
 * @method Doctrine_Collection getCaieRespuestas()                      Returns the current record's "CaieRespuestas" collection
 * @method Doctrine_Collection getCsveRespuestas()                      Returns the current record's "CsveRespuestas" collection
 * @method Doctrine_Collection getDepAdoRespuestas()                    Returns the current record's "DepAdoRespuestas" collection
 * @method Doctrine_Collection getEgedRespuestas()                      Returns the current record's "EgedRespuestas" collection
 * @method Doctrine_Collection getEncuestadoActinputado()               Returns the current record's "EncuestadoActinputado" collection
 * @method Doctrine_Collection getEncuestadoCanteriores()               Returns the current record's "EncuestadoCanteriores" collection
 * @method Doctrine_Collection getEncuestadoSanciones()                 Returns the current record's "EncuestadoSanciones" collection
 * @method Doctrine_Collection getEstadosInstrumentos()                 Returns the current record's "EstadosInstrumentos" collection
 * @method Doctrine_Collection getFerrRespuestas()                      Returns the current record's "FerrRespuestas" collection
 * @method Doctrine_Collection getIrncRespuestas()                      Returns the current record's "IrncRespuestas" collection
 * @method Doctrine_Collection getIrncRespuestas4()                     Returns the current record's "IrncRespuestas_4" collection
 * @method Doctrine_Collection getJirRespuestas()                       Returns the current record's "JirRespuestas" collection
 * @method Doctrine_Collection getMaciRespuestas()                      Returns the current record's "MaciRespuestas" collection
 * @method Doctrine_Collection getSqifaRespuestas()                     Returns the current record's "SqifaRespuestas" collection
 * @method Encuestado          setIdEncuestado()                        Sets the current record's "id_encuestado" value
 * @method Encuestado          setIdUserResponsablePrincipal()          Sets the current record's "id_user_responsable_principal" value
 * @method Encuestado          setSelectUserResponsableSecundario1()    Sets the current record's "select_user_responsable_secundario1" value
 * @method Encuestado          setIdUserResponsableSecundario()         Sets the current record's "id_user_responsable_secundario" value
 * @method Encuestado          setInputRunNconverificador()             Sets the current record's "input_run_nconverificador" value
 * @method Encuestado          setInputPrimerNombre()                   Sets the current record's "input_primer_nombre" value
 * @method Encuestado          setInputOtrosNombres()                   Sets the current record's "input_otros_nombres" value
 * @method Encuestado          setInputPrimerApellido()                 Sets the current record's "input_primer_apellido" value
 * @method Encuestado          setInputSegundoApellido()                Sets the current record's "input_segundo_apellido" value
 * @method Encuestado          setRadioSexo()                           Sets the current record's "radio_sexo" value
 * @method Encuestado          setInputFnacimiento()                    Sets the current record's "input_fnacimiento" value
 * @method Encuestado          setSelectRegion()                        Sets the current record's "select_region" value
 * @method Encuestado          setSelectProvincia()                     Sets the current record's "select_provincia" value
 * @method Encuestado          setSelectComuna()                        Sets the current record's "select_comuna" value
 * @method Encuestado          setRadioProcedencia()                    Sets the current record's "radio_procedencia" value
 * @method Encuestado          setInputLocalidadIndigena()              Sets the current record's "input_localidad_indigena" value
 * @method Encuestado          setSelectOrigenEtnico()                  Sets the current record's "select_origen_etnico" value
 * @method Encuestado          setSelectIngresoFamiliar()               Sets the current record's "select_ingreso_familiar" value
 * @method Encuestado          setSelectResidenciaRegular()             Sets the current record's "select_residencia_regular" value
 * @method Encuestado          setSelectHijo()                          Sets the current record's "select_hijo" value
 * @method Encuestado          setSelectUltimcursoAprobado()            Sets the current record's "select_ultimcurso_aprobado" value
 * @method Encuestado          setInputAnioUltimocurso()                Sets the current record's "input_anio_ultimocurso" value
 * @method Encuestado          setSelectActescEncurso()                 Sets the current record's "select_actesc_encurso" value
 * @method Encuestado          setSelectTipoAsistencia()                Sets the current record's "select_tipo_asistencia" value
 * @method Encuestado          setSelectAsistenciaPconace()             Sets the current record's "select_asistencia_pconace" value
 * @method Encuestado          setSelectTipoPconace()                   Sets the current record's "select_tipo_pconace" value
 * @method Encuestado          setCreatedAt()                           Sets the current record's "created_at" value
 * @method Encuestado          setUpdatedAt()                           Sets the current record's "updated_at" value
 * @method Encuestado          setSelectNacionalidad()                  Sets the current record's "select_nacionalidad" value
 * @method Encuestado          setInputDomicilio()                      Sets the current record's "input_domicilio" value
 * @method Encuestado          setSfGuardUser()                         Sets the current record's "SfGuardUser" value
 * @method Encuestado          setSfGuardUser2()                        Sets the current record's "SfGuardUser_2" value
 * @method Encuestado          setCacsa2Respuestas()                    Sets the current record's "Cacsa2Respuestas" collection
 * @method Encuestado          setCacsa3Respuestas()                    Sets the current record's "Cacsa3Respuestas" collection
 * @method Encuestado          setCaieRespuestas()                      Sets the current record's "CaieRespuestas" collection
 * @method Encuestado          setCsveRespuestas()                      Sets the current record's "CsveRespuestas" collection
 * @method Encuestado          setDepAdoRespuestas()                    Sets the current record's "DepAdoRespuestas" collection
 * @method Encuestado          setEgedRespuestas()                      Sets the current record's "EgedRespuestas" collection
 * @method Encuestado          setEncuestadoActinputado()               Sets the current record's "EncuestadoActinputado" collection
 * @method Encuestado          setEncuestadoCanteriores()               Sets the current record's "EncuestadoCanteriores" collection
 * @method Encuestado          setEncuestadoSanciones()                 Sets the current record's "EncuestadoSanciones" collection
 * @method Encuestado          setEstadosInstrumentos()                 Sets the current record's "EstadosInstrumentos" collection
 * @method Encuestado          setFerrRespuestas()                      Sets the current record's "FerrRespuestas" collection
 * @method Encuestado          setIrncRespuestas()                      Sets the current record's "IrncRespuestas" collection
 * @method Encuestado          setIrncRespuestas4()                     Sets the current record's "IrncRespuestas_4" collection
 * @method Encuestado          setJirRespuestas()                       Sets the current record's "JirRespuestas" collection
 * @method Encuestado          setMaciRespuestas()                      Sets the current record's "MaciRespuestas" collection
 * @method Encuestado          setSqifaRespuestas()                     Sets the current record's "SqifaRespuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEncuestado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuestado');
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_user_responsable_principal', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('select_user_responsable_secundario1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_user_responsable_secundario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('input_run_nconverificador', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('input_primer_nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_otros_nombres', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_primer_apellido', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_segundo_apellido', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('radio_sexo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_fnacimiento', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('select_region', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_provincia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_comuna', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('radio_procedencia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_localidad_indigena', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_origen_etnico', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_ingreso_familiar', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_residencia_regular', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_hijo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_ultimcurso_aprobado', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_anio_ultimocurso', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_actesc_encurso', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_tipo_asistencia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_asistencia_pconace', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_tipo_pconace', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('select_nacionalidad', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('input_domicilio', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user_responsable_principal',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser as SfGuardUser_2', array(
             'local' => 'id_user_responsable_secundario',
             'foreign' => 'id'));

        $this->hasMany('Cacsa2Respuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('Cacsa3Respuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('CaieRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('CsveRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('DepAdoRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('EgedRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('EncuestadoActinputado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('EncuestadoCanteriores', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('EncuestadoSanciones', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('EstadosInstrumentos', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('FerrRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('IrncRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('IrncRespuestas as IrncRespuestas_4', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('JirRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('MaciRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasMany('SqifaRespuestas', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));
    }
}