<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SqifaRespuestas', 'doctrine');

/**
 * BaseSqifaRespuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property string $respuesta
 * @property string $comentario
 * @property integer $id_encuestado
 * @property integer $id_pregunta_sqifa
 * @property SfGuardUser $SfGuardUser
 * @property Encuestado $Encuestado
 * @property SqifaPreguntas $SqifaPreguntas
 * 
 * @method integer         getIdUser()            Returns the current record's "id_user" value
 * @method string          getRespuesta()         Returns the current record's "respuesta" value
 * @method string          getComentario()        Returns the current record's "comentario" value
 * @method integer         getIdEncuestado()      Returns the current record's "id_encuestado" value
 * @method integer         getIdPreguntaSqifa()   Returns the current record's "id_pregunta_sqifa" value
 * @method SfGuardUser     getSfGuardUser()       Returns the current record's "SfGuardUser" value
 * @method Encuestado      getEncuestado()        Returns the current record's "Encuestado" value
 * @method SqifaPreguntas  getSqifaPreguntas()    Returns the current record's "SqifaPreguntas" value
 * @method SqifaRespuestas setIdUser()            Sets the current record's "id_user" value
 * @method SqifaRespuestas setRespuesta()         Sets the current record's "respuesta" value
 * @method SqifaRespuestas setComentario()        Sets the current record's "comentario" value
 * @method SqifaRespuestas setIdEncuestado()      Sets the current record's "id_encuestado" value
 * @method SqifaRespuestas setIdPreguntaSqifa()   Sets the current record's "id_pregunta_sqifa" value
 * @method SqifaRespuestas setSfGuardUser()       Sets the current record's "SfGuardUser" value
 * @method SqifaRespuestas setEncuestado()        Sets the current record's "Encuestado" value
 * @method SqifaRespuestas setSqifaPreguntas()    Sets the current record's "SqifaPreguntas" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSqifaRespuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sqifa_respuestas');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('comentario', 'string', 281, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 281,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pregunta_sqifa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('SqifaPreguntas', array(
             'local' => 'id_pregunta_sqifa',
             'foreign' => 'id_pregunta_sqifa'));
    }
}