<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CIngresoCausa', 'doctrine');

/**
 * BaseCIngresoCausa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_materia
 * @property integer $id_causa
 * @property string $causa_nombre
 * @property integer $codigo_delito
 * @property CIngresoMateria $CIngresoMateria
 * @property Doctrine_Collection $EncuestadoActinputado
 * 
 * @method integer             getIdMateria()             Returns the current record's "id_materia" value
 * @method integer             getIdCausa()               Returns the current record's "id_causa" value
 * @method string              getCausaNombre()           Returns the current record's "causa_nombre" value
 * @method integer             getCodigoDelito()          Returns the current record's "codigo_delito" value
 * @method CIngresoMateria     getCIngresoMateria()       Returns the current record's "CIngresoMateria" value
 * @method Doctrine_Collection getEncuestadoActinputado() Returns the current record's "EncuestadoActinputado" collection
 * @method CIngresoCausa       setIdMateria()             Sets the current record's "id_materia" value
 * @method CIngresoCausa       setIdCausa()               Sets the current record's "id_causa" value
 * @method CIngresoCausa       setCausaNombre()           Sets the current record's "causa_nombre" value
 * @method CIngresoCausa       setCodigoDelito()          Sets the current record's "codigo_delito" value
 * @method CIngresoCausa       setCIngresoMateria()       Sets the current record's "CIngresoMateria" value
 * @method CIngresoCausa       setEncuestadoActinputado() Sets the current record's "EncuestadoActinputado" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCIngresoCausa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('c_ingreso_causa');
        $this->hasColumn('id_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_causa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('causa_nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('codigo_delito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CIngresoMateria', array(
             'local' => 'id_materia',
             'foreign' => 'id_materia'));

        $this->hasMany('EncuestadoActinputado', array(
             'local' => 'codigo_delito',
             'foreign' => 'select_causa_delito3'));
    }
}