<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CaiePreguntas', 'doctrine');

/**
 * BaseCaiePreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_caie
 * @property integer $num_pregunta
 * @property string $texto
 * @property integer $es_requerido
 * @property Doctrine_Collection $CaieRespuestas
 * 
 * @method integer             getIdPreguntaCaie()   Returns the current record's "id_pregunta_caie" value
 * @method integer             getNumPregunta()      Returns the current record's "num_pregunta" value
 * @method string              getTexto()            Returns the current record's "texto" value
 * @method integer             getEsRequerido()      Returns the current record's "es_requerido" value
 * @method Doctrine_Collection getCaieRespuestas()   Returns the current record's "CaieRespuestas" collection
 * @method CaiePreguntas       setIdPreguntaCaie()   Sets the current record's "id_pregunta_caie" value
 * @method CaiePreguntas       setNumPregunta()      Sets the current record's "num_pregunta" value
 * @method CaiePreguntas       setTexto()            Sets the current record's "texto" value
 * @method CaiePreguntas       setEsRequerido()      Sets the current record's "es_requerido" value
 * @method CaiePreguntas       setCaieRespuestas()   Sets the current record's "CaieRespuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCaiePreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('caie_preguntas');
        $this->hasColumn('id_pregunta_caie', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CaieRespuestas', array(
             'local' => 'id_pregunta_caie',
             'foreign' => 'id_pregunta_caie'));
    }
}