<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JirPreguntas', 'doctrine');

/**
 * BaseJirPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_jir
 * @property integer $num_pregunta
 * @property string $texto
 * @property integer $es_requerido
 * @property Doctrine_Collection $JirRespuestas
 * 
 * @method integer             getIdPreguntaJir()   Returns the current record's "id_pregunta_jir" value
 * @method integer             getNumPregunta()     Returns the current record's "num_pregunta" value
 * @method string              getTexto()           Returns the current record's "texto" value
 * @method integer             getEsRequerido()     Returns the current record's "es_requerido" value
 * @method Doctrine_Collection getJirRespuestas()   Returns the current record's "JirRespuestas" collection
 * @method JirPreguntas        setIdPreguntaJir()   Sets the current record's "id_pregunta_jir" value
 * @method JirPreguntas        setNumPregunta()     Sets the current record's "num_pregunta" value
 * @method JirPreguntas        setTexto()           Sets the current record's "texto" value
 * @method JirPreguntas        setEsRequerido()     Sets the current record's "es_requerido" value
 * @method JirPreguntas        setJirRespuestas()   Sets the current record's "JirRespuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJirPreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jir_preguntas');
        $this->hasColumn('id_pregunta_jir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JirRespuestas', array(
             'local' => 'id_pregunta_jir',
             'foreign' => 'id_pregunta_jir'));
    }
}