<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EncuestadoCanteriores', 'doctrine');

/**
 * BaseEncuestadoCanteriores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $input_fecha_inicio_condena2
 * @property timestamp $input_fecha_termino_condena2
 * @property string $select_tribunal2
 * @property string $select_tipo_materia2
 * @property string $select_causa_delito2
 * @property integer $id_encuestado
 * @property string $input_ruk2
 * @property string $input_fecha_detencion2
 * @property string $input_fecha_control_detencion2
 * @property Encuestado $Encuestado
 * 
 * @method integer               getId()                             Returns the current record's "id" value
 * @method timestamp             getInputFechaInicioCondena2()       Returns the current record's "input_fecha_inicio_condena2" value
 * @method timestamp             getInputFechaTerminoCondena2()      Returns the current record's "input_fecha_termino_condena2" value
 * @method string                getSelectTribunal2()                Returns the current record's "select_tribunal2" value
 * @method string                getSelectTipoMateria2()             Returns the current record's "select_tipo_materia2" value
 * @method string                getSelectCausaDelito2()             Returns the current record's "select_causa_delito2" value
 * @method integer               getIdEncuestado()                   Returns the current record's "id_encuestado" value
 * @method string                getInputRuk2()                      Returns the current record's "input_ruk2" value
 * @method string                getInputFechaDetencion2()           Returns the current record's "input_fecha_detencion2" value
 * @method string                getInputFechaControlDetencion2()    Returns the current record's "input_fecha_control_detencion2" value
 * @method Encuestado            getEncuestado()                     Returns the current record's "Encuestado" value
 * @method EncuestadoCanteriores setId()                             Sets the current record's "id" value
 * @method EncuestadoCanteriores setInputFechaInicioCondena2()       Sets the current record's "input_fecha_inicio_condena2" value
 * @method EncuestadoCanteriores setInputFechaTerminoCondena2()      Sets the current record's "input_fecha_termino_condena2" value
 * @method EncuestadoCanteriores setSelectTribunal2()                Sets the current record's "select_tribunal2" value
 * @method EncuestadoCanteriores setSelectTipoMateria2()             Sets the current record's "select_tipo_materia2" value
 * @method EncuestadoCanteriores setSelectCausaDelito2()             Sets the current record's "select_causa_delito2" value
 * @method EncuestadoCanteriores setIdEncuestado()                   Sets the current record's "id_encuestado" value
 * @method EncuestadoCanteriores setInputRuk2()                      Sets the current record's "input_ruk2" value
 * @method EncuestadoCanteriores setInputFechaDetencion2()           Sets the current record's "input_fecha_detencion2" value
 * @method EncuestadoCanteriores setInputFechaControlDetencion2()    Sets the current record's "input_fecha_control_detencion2" value
 * @method EncuestadoCanteriores setEncuestado()                     Sets the current record's "Encuestado" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEncuestadoCanteriores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuestado_canteriores');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('input_fecha_inicio_condena2', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('input_fecha_termino_condena2', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('select_tribunal2', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('select_tipo_materia2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_causa_delito2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('input_ruk2', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('input_fecha_detencion2', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('input_fecha_control_detencion2', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));
    }
}