<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cacsa2Respuestas', 'doctrine');

/**
 * BaseCacsa2Respuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property integer $respuesta
 * @property string $respuesta2
 * @property string $comentario
 * @property integer $id_encuestado
 * @property integer $id_pregunta_cacsa2
 * @property SfGuardUser $SfGuardUser
 * @property Encuestado $Encuestado
 * @property Cacsa2Preguntas $Cacsa2Preguntas
 * 
 * @method integer          getIdUser()             Returns the current record's "id_user" value
 * @method integer          getRespuesta()          Returns the current record's "respuesta" value
 * @method string           getRespuesta2()         Returns the current record's "respuesta2" value
 * @method string           getComentario()         Returns the current record's "comentario" value
 * @method integer          getIdEncuestado()       Returns the current record's "id_encuestado" value
 * @method integer          getIdPreguntaCacsa2()   Returns the current record's "id_pregunta_cacsa2" value
 * @method SfGuardUser      getSfGuardUser()        Returns the current record's "SfGuardUser" value
 * @method Encuestado       getEncuestado()         Returns the current record's "Encuestado" value
 * @method Cacsa2Preguntas  getCacsa2Preguntas()    Returns the current record's "Cacsa2Preguntas" value
 * @method Cacsa2Respuestas setIdUser()             Sets the current record's "id_user" value
 * @method Cacsa2Respuestas setRespuesta()          Sets the current record's "respuesta" value
 * @method Cacsa2Respuestas setRespuesta2()         Sets the current record's "respuesta2" value
 * @method Cacsa2Respuestas setComentario()         Sets the current record's "comentario" value
 * @method Cacsa2Respuestas setIdEncuestado()       Sets the current record's "id_encuestado" value
 * @method Cacsa2Respuestas setIdPreguntaCacsa2()   Sets the current record's "id_pregunta_cacsa2" value
 * @method Cacsa2Respuestas setSfGuardUser()        Sets the current record's "SfGuardUser" value
 * @method Cacsa2Respuestas setEncuestado()         Sets the current record's "Encuestado" value
 * @method Cacsa2Respuestas setCacsa2Preguntas()    Sets the current record's "Cacsa2Preguntas" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCacsa2Respuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cacsa2_respuestas');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('respuesta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('comentario', 'string', 281, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 281,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pregunta_cacsa2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('Cacsa2Preguntas', array(
             'local' => 'id_pregunta_cacsa2',
             'foreign' => 'id_pregunta_cacsa2'));
    }
}