<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DepAdoPreguntas', 'doctrine');

/**
 * BaseDepAdoPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_dep_ado
 * @property string $num_pregunta
 * @property string $texto
 * @property integer $es_requerido
 * @property string $bloque_dep_ado
 * @property integer $bloque_num
 * @property Doctrine_Collection $DepAdoRespuestas
 * 
 * @method integer             getIdPreguntaDepAdo()    Returns the current record's "id_pregunta_dep_ado" value
 * @method string              getNumPregunta()         Returns the current record's "num_pregunta" value
 * @method string              getTexto()               Returns the current record's "texto" value
 * @method integer             getEsRequerido()         Returns the current record's "es_requerido" value
 * @method string              getBloqueDepAdo()        Returns the current record's "bloque_dep_ado" value
 * @method integer             getBloqueNum()           Returns the current record's "bloque_num" value
 * @method Doctrine_Collection getDepAdoRespuestas()    Returns the current record's "DepAdoRespuestas" collection
 * @method DepAdoPreguntas     setIdPreguntaDepAdo()    Sets the current record's "id_pregunta_dep_ado" value
 * @method DepAdoPreguntas     setNumPregunta()         Sets the current record's "num_pregunta" value
 * @method DepAdoPreguntas     setTexto()               Sets the current record's "texto" value
 * @method DepAdoPreguntas     setEsRequerido()         Sets the current record's "es_requerido" value
 * @method DepAdoPreguntas     setBloqueDepAdo()        Sets the current record's "bloque_dep_ado" value
 * @method DepAdoPreguntas     setBloqueNum()           Sets the current record's "bloque_num" value
 * @method DepAdoPreguntas     setDepAdoRespuestas()    Sets the current record's "DepAdoRespuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepAdoPreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dep_ado_preguntas');
        $this->hasColumn('id_pregunta_dep_ado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('bloque_dep_ado', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('bloque_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DepAdoRespuestas', array(
             'local' => 'id_pregunta_dep_ado',
             'foreign' => 'id_pregunta_dep_ado'));
    }
}