<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FerrRespuestas', 'doctrine');

/**
 * BaseFerrRespuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property string $respuesta
 * @property integer $id_encuestado
 * @property integer $id_respuesta
 * @property SfGuardUser $SfGuardUser
 * @property Encuestado $Encuestado
 * 
 * @method integer        getIdUser()        Returns the current record's "id_user" value
 * @method string         getRespuesta()     Returns the current record's "respuesta" value
 * @method integer        getIdEncuestado()  Returns the current record's "id_encuestado" value
 * @method integer        getIdRespuesta()   Returns the current record's "id_respuesta" value
 * @method SfGuardUser    getSfGuardUser()   Returns the current record's "SfGuardUser" value
 * @method Encuestado     getEncuestado()    Returns the current record's "Encuestado" value
 * @method FerrRespuestas setIdUser()        Sets the current record's "id_user" value
 * @method FerrRespuestas setRespuesta()     Sets the current record's "respuesta" value
 * @method FerrRespuestas setIdEncuestado()  Sets the current record's "id_encuestado" value
 * @method FerrRespuestas setIdRespuesta()   Sets the current record's "id_respuesta" value
 * @method FerrRespuestas setSfGuardUser()   Sets the current record's "SfGuardUser" value
 * @method FerrRespuestas setEncuestado()    Sets the current record's "Encuestado" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFerrRespuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ferr_respuestas');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_respuesta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));
    }
}