<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ferr2', 'doctrine');

/**
 * BaseFerr2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_respuesta
 * @property integer $id_user
 * @property integer $id_encuestado
 * @property string $respuesta
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getIdRespuesta()   Returns the current record's "id_respuesta" value
 * @method integer getIdUser()        Returns the current record's "id_user" value
 * @method integer getIdEncuestado()  Returns the current record's "id_encuestado" value
 * @method string  getRespuesta()     Returns the current record's "respuesta" value
 * @method Ferr2   setId()            Sets the current record's "id" value
 * @method Ferr2   setIdRespuesta()   Sets the current record's "id_respuesta" value
 * @method Ferr2   setIdUser()        Sets the current record's "id_user" value
 * @method Ferr2   setIdEncuestado()  Sets the current record's "id_encuestado" value
 * @method Ferr2   setRespuesta()     Sets the current record's "respuesta" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFerr2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ferr2');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_encuestado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}