<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EncuestadoSanciones', 'doctrine');

/**
 * BaseEncuestadoSanciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $select_sistema_atencion
 * @property string $input_nombre_programa
 * @property string $select_ciudad_programa
 * @property integer $input_tiempo_total_condena
 * @property timestamp $input_fecha_inicio_condena
 * @property string $select_tipo_materia
 * @property string $select_causa_delito
 * @property integer $id_encuestado
 * @property string $select_tipo_tiempo_total_condena
 * @property string $input_ruk
 * @property string $input_fecha_detencion
 * @property string $input_fecha_control_detencion
 * @property Encuestado $Encuestado
 * 
 * @method integer             getId()                               Returns the current record's "id" value
 * @method string              getSelectSistemaAtencion()            Returns the current record's "select_sistema_atencion" value
 * @method string              getInputNombrePrograma()              Returns the current record's "input_nombre_programa" value
 * @method string              getSelectCiudadPrograma()             Returns the current record's "select_ciudad_programa" value
 * @method integer             getInputTiempoTotalCondena()          Returns the current record's "input_tiempo_total_condena" value
 * @method timestamp           getInputFechaInicioCondena()          Returns the current record's "input_fecha_inicio_condena" value
 * @method string              getSelectTipoMateria()                Returns the current record's "select_tipo_materia" value
 * @method string              getSelectCausaDelito()                Returns the current record's "select_causa_delito" value
 * @method integer             getIdEncuestado()                     Returns the current record's "id_encuestado" value
 * @method string              getSelectTipoTiempoTotalCondena()     Returns the current record's "select_tipo_tiempo_total_condena" value
 * @method string              getInputRuk()                         Returns the current record's "input_ruk" value
 * @method string              getInputFechaDetencion()              Returns the current record's "input_fecha_detencion" value
 * @method string              getInputFechaControlDetencion()       Returns the current record's "input_fecha_control_detencion" value
 * @method Encuestado          getEncuestado()                       Returns the current record's "Encuestado" value
 * @method EncuestadoSanciones setId()                               Sets the current record's "id" value
 * @method EncuestadoSanciones setSelectSistemaAtencion()            Sets the current record's "select_sistema_atencion" value
 * @method EncuestadoSanciones setInputNombrePrograma()              Sets the current record's "input_nombre_programa" value
 * @method EncuestadoSanciones setSelectCiudadPrograma()             Sets the current record's "select_ciudad_programa" value
 * @method EncuestadoSanciones setInputTiempoTotalCondena()          Sets the current record's "input_tiempo_total_condena" value
 * @method EncuestadoSanciones setInputFechaInicioCondena()          Sets the current record's "input_fecha_inicio_condena" value
 * @method EncuestadoSanciones setSelectTipoMateria()                Sets the current record's "select_tipo_materia" value
 * @method EncuestadoSanciones setSelectCausaDelito()                Sets the current record's "select_causa_delito" value
 * @method EncuestadoSanciones setIdEncuestado()                     Sets the current record's "id_encuestado" value
 * @method EncuestadoSanciones setSelectTipoTiempoTotalCondena()     Sets the current record's "select_tipo_tiempo_total_condena" value
 * @method EncuestadoSanciones setInputRuk()                         Sets the current record's "input_ruk" value
 * @method EncuestadoSanciones setInputFechaDetencion()              Sets the current record's "input_fecha_detencion" value
 * @method EncuestadoSanciones setInputFechaControlDetencion()       Sets the current record's "input_fecha_control_detencion" value
 * @method EncuestadoSanciones setEncuestado()                       Sets the current record's "Encuestado" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEncuestadoSanciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuestado_sanciones');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('select_sistema_atencion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_nombre_programa', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_ciudad_programa', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_tiempo_total_condena', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('input_fecha_inicio_condena', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('select_tipo_materia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('select_causa_delito', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('select_tipo_tiempo_total_condena', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('input_ruk', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('input_fecha_detencion', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('input_fecha_control_detencion', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));
    }
}