<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CesmaPreguntas', 'doctrine');

/**
 * BaseCesmaPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_cesma
 * @property integer $num_pregunta
 * @property string $texto
 * @property integer $es_requerido
 * @property integer $bloque_num
 * 
 * @method integer        getIdPreguntaCesma()   Returns the current record's "id_pregunta_cesma" value
 * @method integer        getNumPregunta()       Returns the current record's "num_pregunta" value
 * @method string         getTexto()             Returns the current record's "texto" value
 * @method integer        getEsRequerido()       Returns the current record's "es_requerido" value
 * @method integer        getBloqueNum()         Returns the current record's "bloque_num" value
 * @method CesmaPreguntas setIdPreguntaCesma()   Sets the current record's "id_pregunta_cesma" value
 * @method CesmaPreguntas setNumPregunta()       Sets the current record's "num_pregunta" value
 * @method CesmaPreguntas setTexto()             Sets the current record's "texto" value
 * @method CesmaPreguntas setEsRequerido()       Sets the current record's "es_requerido" value
 * @method CesmaPreguntas setBloqueNum()         Sets the current record's "bloque_num" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCesmaPreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cesma_preguntas');
        $this->hasColumn('id_pregunta_cesma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('bloque_num', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}