<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IrncRespuestas', 'doctrine');

/**
 * BaseIrncRespuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property string $respuesta
 * @property string $comentario
 * @property integer $id_encuestado
 * @property integer $id_pregunta_irnc
 * @property SfGuardUser $SfGuardUser
 * @property SfGuardUser $SfGuardUser_2
 * @property Encuestado $Encuestado
 * @property Encuestado $Encuestado_4
 * @property IrncPreguntas $IrncPreguntas
 * 
 * @method integer        getIdUser()           Returns the current record's "id_user" value
 * @method string         getRespuesta()        Returns the current record's "respuesta" value
 * @method string         getComentario()       Returns the current record's "comentario" value
 * @method integer        getIdEncuestado()     Returns the current record's "id_encuestado" value
 * @method integer        getIdPreguntaIrnc()   Returns the current record's "id_pregunta_irnc" value
 * @method SfGuardUser    getSfGuardUser()      Returns the current record's "SfGuardUser" value
 * @method SfGuardUser    getSfGuardUser2()     Returns the current record's "SfGuardUser_2" value
 * @method Encuestado     getEncuestado()       Returns the current record's "Encuestado" value
 * @method Encuestado     getEncuestado4()      Returns the current record's "Encuestado_4" value
 * @method IrncPreguntas  getIrncPreguntas()    Returns the current record's "IrncPreguntas" value
 * @method IrncRespuestas setIdUser()           Sets the current record's "id_user" value
 * @method IrncRespuestas setRespuesta()        Sets the current record's "respuesta" value
 * @method IrncRespuestas setComentario()       Sets the current record's "comentario" value
 * @method IrncRespuestas setIdEncuestado()     Sets the current record's "id_encuestado" value
 * @method IrncRespuestas setIdPreguntaIrnc()   Sets the current record's "id_pregunta_irnc" value
 * @method IrncRespuestas setSfGuardUser()      Sets the current record's "SfGuardUser" value
 * @method IrncRespuestas setSfGuardUser2()     Sets the current record's "SfGuardUser_2" value
 * @method IrncRespuestas setEncuestado()       Sets the current record's "Encuestado" value
 * @method IrncRespuestas setEncuestado4()      Sets the current record's "Encuestado_4" value
 * @method IrncRespuestas setIrncPreguntas()    Sets the current record's "IrncPreguntas" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIrncRespuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('irnc_respuestas');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('comentario', 'string', 281, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 281,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pregunta_irnc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser as SfGuardUser_2', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('Encuestado as Encuestado_4', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('IrncPreguntas', array(
             'local' => 'id_pregunta_irnc',
             'foreign' => 'id_pregunta_irnc'));
    }
}