<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ferr2Respuestas', 'doctrine');

/**
 * BaseFerr2Respuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_respuesta
 * @property string $respuesta
 * @property integer $id_user
 * @property integer $id_encuestado
 * @property integer $concensomode
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method string          getIdRespuesta()   Returns the current record's "id_respuesta" value
 * @method string          getRespuesta()     Returns the current record's "respuesta" value
 * @method integer         getIdUser()        Returns the current record's "id_user" value
 * @method integer         getIdEncuestado()  Returns the current record's "id_encuestado" value
 * @method integer         getConcensomode()  Returns the current record's "concensomode" value
 * @method Ferr2Respuestas setId()            Sets the current record's "id" value
 * @method Ferr2Respuestas setIdRespuesta()   Sets the current record's "id_respuesta" value
 * @method Ferr2Respuestas setRespuesta()     Sets the current record's "respuesta" value
 * @method Ferr2Respuestas setIdUser()        Sets the current record's "id_user" value
 * @method Ferr2Respuestas setIdEncuestado()  Sets the current record's "id_encuestado" value
 * @method Ferr2Respuestas setConcensomode()  Sets the current record's "concensomode" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFerr2Respuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ferr2_respuestas');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('concensomode', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}