<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Provincia', 'doctrine');

/**
 * BaseProvincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $provincia_id
 * @property string $provincia_nombre
 * @property integer $provincia_region_id
 * @property Region $Region
 * @property Doctrine_Collection $Comuna
 * 
 * @method integer             getProvinciaId()         Returns the current record's "provincia_id" value
 * @method string              getProvinciaNombre()     Returns the current record's "provincia_nombre" value
 * @method integer             getProvinciaRegionId()   Returns the current record's "provincia_region_id" value
 * @method Region              getRegion()              Returns the current record's "Region" value
 * @method Doctrine_Collection getComuna()              Returns the current record's "Comuna" collection
 * @method Provincia           setProvinciaId()         Sets the current record's "provincia_id" value
 * @method Provincia           setProvinciaNombre()     Sets the current record's "provincia_nombre" value
 * @method Provincia           setProvinciaRegionId()   Sets the current record's "provincia_region_id" value
 * @method Provincia           setRegion()              Sets the current record's "Region" value
 * @method Provincia           setComuna()              Sets the current record's "Comuna" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvincia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('provincia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('provincia_nombre', 'string', 23, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 23,
             ));
        $this->hasColumn('provincia_region_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'provincia_region_id',
             'foreign' => 'region_id'));

        $this->hasMany('Comuna', array(
             'local' => 'provincia_id',
             'foreign' => 'comuna_provincia_id'));
    }
}