<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Test', 'doctrine');

/**
 * BaseTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $prueba1
 * @property string $texto
 * @property integer $idtest
 * 
 * @method integer getPrueba1() Returns the current record's "prueba1" value
 * @method string  getTexto()   Returns the current record's "texto" value
 * @method integer getIdtest()  Returns the current record's "idtest" value
 * @method Test    setPrueba1() Sets the current record's "prueba1" value
 * @method Test    setTexto()   Sets the current record's "texto" value
 * @method Test    setIdtest()  Sets the current record's "idtest" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test');
        $this->hasColumn('prueba1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('idtest', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}