<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Region', 'doctrine');

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $region_id
 * @property string $region_nombre
 * @property Doctrine_Collection $Provincia
 * 
 * @method integer             getRegionId()      Returns the current record's "region_id" value
 * @method string              getRegionNombre()  Returns the current record's "region_nombre" value
 * @method Doctrine_Collection getProvincia()     Returns the current record's "Provincia" collection
 * @method Region              setRegionId()      Sets the current record's "region_id" value
 * @method Region              setRegionNombre()  Sets the current record's "region_nombre" value
 * @method Region              setProvincia()     Sets the current record's "Provincia" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('region_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('region_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Provincia', array(
             'local' => 'region_id',
             'foreign' => 'provincia_region_id'));
    }
}