<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CsveRespuestas', 'doctrine');

/**
 * BaseCsveRespuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property string $respuesta
 * @property integer $respuesta2
 * @property string $respuesta3
 * @property string $comentario
 * @property integer $id_encuestado
 * @property integer $id_pregunta_csve
 * @property SfGuardUser $SfGuardUser
 * @property Encuestado $Encuestado
 * @property CsvePreguntas $CsvePreguntas
 * 
 * @method integer        getIdUser()           Returns the current record's "id_user" value
 * @method string         getRespuesta()        Returns the current record's "respuesta" value
 * @method integer        getRespuesta2()       Returns the current record's "respuesta2" value
 * @method string         getRespuesta3()       Returns the current record's "respuesta3" value
 * @method string         getComentario()       Returns the current record's "comentario" value
 * @method integer        getIdEncuestado()     Returns the current record's "id_encuestado" value
 * @method integer        getIdPreguntaCsve()   Returns the current record's "id_pregunta_csve" value
 * @method SfGuardUser    getSfGuardUser()      Returns the current record's "SfGuardUser" value
 * @method Encuestado     getEncuestado()       Returns the current record's "Encuestado" value
 * @method CsvePreguntas  getCsvePreguntas()    Returns the current record's "CsvePreguntas" value
 * @method CsveRespuestas setIdUser()           Sets the current record's "id_user" value
 * @method CsveRespuestas setRespuesta()        Sets the current record's "respuesta" value
 * @method CsveRespuestas setRespuesta2()       Sets the current record's "respuesta2" value
 * @method CsveRespuestas setRespuesta3()       Sets the current record's "respuesta3" value
 * @method CsveRespuestas setComentario()       Sets the current record's "comentario" value
 * @method CsveRespuestas setIdEncuestado()     Sets the current record's "id_encuestado" value
 * @method CsveRespuestas setIdPreguntaCsve()   Sets the current record's "id_pregunta_csve" value
 * @method CsveRespuestas setSfGuardUser()      Sets the current record's "SfGuardUser" value
 * @method CsveRespuestas setEncuestado()       Sets the current record's "Encuestado" value
 * @method CsveRespuestas setCsvePreguntas()    Sets the current record's "CsvePreguntas" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCsveRespuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csve_respuestas');
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('respuesta', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('respuesta2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta3', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('comentario', 'string', 281, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 281,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pregunta_csve', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('CsvePreguntas', array(
             'local' => 'id_pregunta_csve',
             'foreign' => 'id_pregunta_csve'));
    }
}