<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cacsa3Preguntas', 'doctrine');

/**
 * BaseCacsa3Preguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_cacsa3
 * @property integer $num_pregunta
 * @property string $texto
 * @property integer $es_requerido
 * @property Doctrine_Collection $Cacsa3Respuestas
 * 
 * @method integer             getIdPreguntaCacsa3()   Returns the current record's "id_pregunta_cacsa3" value
 * @method integer             getNumPregunta()        Returns the current record's "num_pregunta" value
 * @method string              getTexto()              Returns the current record's "texto" value
 * @method integer             getEsRequerido()        Returns the current record's "es_requerido" value
 * @method Doctrine_Collection getCacsa3Respuestas()   Returns the current record's "Cacsa3Respuestas" collection
 * @method Cacsa3Preguntas     setIdPreguntaCacsa3()   Sets the current record's "id_pregunta_cacsa3" value
 * @method Cacsa3Preguntas     setNumPregunta()        Sets the current record's "num_pregunta" value
 * @method Cacsa3Preguntas     setTexto()              Sets the current record's "texto" value
 * @method Cacsa3Preguntas     setEsRequerido()        Sets the current record's "es_requerido" value
 * @method Cacsa3Preguntas     setCacsa3Respuestas()   Sets the current record's "Cacsa3Respuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCacsa3Preguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cacsa3_preguntas');
        $this->hasColumn('id_pregunta_cacsa3', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cacsa3Respuestas', array(
             'local' => 'id_pregunta_cacsa3',
             'foreign' => 'id_pregunta_cacsa3'));
    }
}