<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EncuestadoActinputado', 'doctrine');

/**
 * BaseEncuestadoActinputado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $input_fecha_inicio_investigacion3
 * @property date $input_plazo_investigacion3
 * @property string $select_tribunal3
 * @property integer $select_tipo_materia3
 * @property integer $select_causa_delito3
 * @property integer $id_encuestado
 * @property string $input_ruk3
 * @property Encuestado $Encuestado
 * @property CIngresoMateria $CIngresoMateria
 * @property CIngresoCausa $CIngresoCausa
 * 
 * @method integer               getId()                                Returns the current record's "id" value
 * @method date                  getInputFechaInicioInvestigacion3()    Returns the current record's "input_fecha_inicio_investigacion3" value
 * @method date                  getInputPlazoInvestigacion3()          Returns the current record's "input_plazo_investigacion3" value
 * @method string                getSelectTribunal3()                   Returns the current record's "select_tribunal3" value
 * @method integer               getSelectTipoMateria3()                Returns the current record's "select_tipo_materia3" value
 * @method integer               getSelectCausaDelito3()                Returns the current record's "select_causa_delito3" value
 * @method integer               getIdEncuestado()                      Returns the current record's "id_encuestado" value
 * @method string                getInputRuk3()                         Returns the current record's "input_ruk3" value
 * @method Encuestado            getEncuestado()                        Returns the current record's "Encuestado" value
 * @method CIngresoMateria       getCIngresoMateria()                   Returns the current record's "CIngresoMateria" value
 * @method CIngresoCausa         getCIngresoCausa()                     Returns the current record's "CIngresoCausa" value
 * @method EncuestadoActinputado setId()                                Sets the current record's "id" value
 * @method EncuestadoActinputado setInputFechaInicioInvestigacion3()    Sets the current record's "input_fecha_inicio_investigacion3" value
 * @method EncuestadoActinputado setInputPlazoInvestigacion3()          Sets the current record's "input_plazo_investigacion3" value
 * @method EncuestadoActinputado setSelectTribunal3()                   Sets the current record's "select_tribunal3" value
 * @method EncuestadoActinputado setSelectTipoMateria3()                Sets the current record's "select_tipo_materia3" value
 * @method EncuestadoActinputado setSelectCausaDelito3()                Sets the current record's "select_causa_delito3" value
 * @method EncuestadoActinputado setIdEncuestado()                      Sets the current record's "id_encuestado" value
 * @method EncuestadoActinputado setInputRuk3()                         Sets the current record's "input_ruk3" value
 * @method EncuestadoActinputado setEncuestado()                        Sets the current record's "Encuestado" value
 * @method EncuestadoActinputado setCIngresoMateria()                   Sets the current record's "CIngresoMateria" value
 * @method EncuestadoActinputado setCIngresoCausa()                     Sets the current record's "CIngresoCausa" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEncuestadoActinputado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuestado_actinputado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('input_fecha_inicio_investigacion3', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('input_plazo_investigacion3', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('select_tribunal3', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
        $this->hasColumn('select_tipo_materia3', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('select_causa_delito3', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_encuestado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('input_ruk3', 'string', 254, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 254,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Encuestado', array(
             'local' => 'id_encuestado',
             'foreign' => 'id_encuestado'));

        $this->hasOne('CIngresoMateria', array(
             'local' => 'select_tipo_materia3',
             'foreign' => 'id_materia'));

        $this->hasOne('CIngresoCausa', array(
             'local' => 'select_causa_delito3',
             'foreign' => 'codigo_delito'));
    }
}