<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EgedPreguntas', 'doctrine');

/**
 * BaseEgedPreguntas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pregunta_eged
 * @property integer $num_pregunta
 * @property string $texto
 * @property string $instruccion
 * @property integer $es_requerido
 * @property Doctrine_Collection $EgedRespuestas
 * 
 * @method integer             getIdPreguntaEged()   Returns the current record's "id_pregunta_eged" value
 * @method integer             getNumPregunta()      Returns the current record's "num_pregunta" value
 * @method string              getTexto()            Returns the current record's "texto" value
 * @method string              getInstruccion()      Returns the current record's "instruccion" value
 * @method integer             getEsRequerido()      Returns the current record's "es_requerido" value
 * @method Doctrine_Collection getEgedRespuestas()   Returns the current record's "EgedRespuestas" collection
 * @method EgedPreguntas       setIdPreguntaEged()   Sets the current record's "id_pregunta_eged" value
 * @method EgedPreguntas       setNumPregunta()      Sets the current record's "num_pregunta" value
 * @method EgedPreguntas       setTexto()            Sets the current record's "texto" value
 * @method EgedPreguntas       setInstruccion()      Sets the current record's "instruccion" value
 * @method EgedPreguntas       setEsRequerido()      Sets the current record's "es_requerido" value
 * @method EgedPreguntas       setEgedRespuestas()   Sets the current record's "EgedRespuestas" collection
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEgedPreguntas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eged_preguntas');
        $this->hasColumn('id_pregunta_eged', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('instruccion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('es_requerido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EgedRespuestas', array(
             'local' => 'id_pregunta_eged',
             'foreign' => 'id_pregunta_eged'));
    }
}