<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comuna', 'doctrine');

/**
 * BaseComuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comuna_id
 * @property string $comuna_nombre
 * @property integer $comuna_provincia_id
 * @property Provincia $Provincia
 * 
 * @method integer   getComunaId()            Returns the current record's "comuna_id" value
 * @method string    getComunaNombre()        Returns the current record's "comuna_nombre" value
 * @method integer   getComunaProvinciaId()   Returns the current record's "comuna_provincia_id" value
 * @method Provincia getProvincia()           Returns the current record's "Provincia" value
 * @method Comuna    setComunaId()            Sets the current record's "comuna_id" value
 * @method Comuna    setComunaNombre()        Sets the current record's "comuna_nombre" value
 * @method Comuna    setComunaProvinciaId()   Sets the current record's "comuna_provincia_id" value
 * @method Comuna    setProvincia()           Sets the current record's "Provincia" value
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComuna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comuna');
        $this->hasColumn('comuna_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comuna_nombre', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comuna_provincia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Provincia', array(
             'local' => 'comuna_provincia_id',
             'foreign' => 'provincia_id'));
    }
}