<?php

/**
 * FcmfRespuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FcmfRespuestas extends BaseFcmfRespuestas
{

}