<?php

/**
 * Ferr2Respuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    psicologia
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ferr2Respuestas extends BaseFerr2Respuestas
{

}