<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/27 23:18:48
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_database_db_name' => 'psico',
  'app_database_db_host' => 'localhost',
  'app_database_db_user' => 'root',
  'app_database_db_pass' => NULL,
  'app_supercontrolador_blacklist_FERR' => array (
  0 => 'module',
  1 => 'action',
  2 => 'Guardar',
),
));
