<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/27 23:18:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=psico',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
