<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/27 23:18:48
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'homeSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('author', 'Gustavo Lacoste &lt;gustavo@lacosox.org&gt;, Carlos Henriquez &lt;carlos.henriquez.lara@gmail.com&gt;, Absalon Valdes O. &lt;absalon.valdes@hotmail.com&gt;', false, false);
  $response->addMeta('copyright', 'Licensed under GPL and MIT.', false, false);
  $response->addMeta('title', 'Sitema de registro de adolecentes infractores de ley', false, false);
  $response->addMeta('description', 'Proyecto FONDEF d08i1205 (ESTRATEGIA ECOSISTÉMICA ESPECIALIZADA DE INTERVENCIÓN DIFERENCIADA PARA FAVORECER LA INTEGRACIÓN PSI COSOCIAL DE ADOLESCENTES INFRACTORES DE LEY)', false, false);
  $response->addMeta('keywords', 'psicologia,psico, delitos,d08i1205,', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'all', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('text.css', '', array ());
  $response->addStylesheet('redmond/jquery-ui-1.8.1.custom.css', '', array ());
  $response->addStylesheet('960.css', '', array ());
  $response->addStylesheet('formee/css/form-structure.css', '', array ());
  $response->addStylesheet('formee/css/form-style.css', '', array ());
  $response->addStylesheet('style-dialog-calendars.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('ayuda.css', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.1.custom.min.js', '', array ());
  $response->addJavascript('jquery.history.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('jquery.validate.js', '', array ());
  $response->addJavascript('jquery.Rut.min.js', '', array ());
  $response->addJavascript('funciones_global.js', '', array ());
  $response->addJavascript('jquery.cookie.js', '', array ());
  $response->addJavascript('funciones_Ayuda.js', '', array ());
  $response->addJavascript('funciones_Timer.js', '', array ());
  $response->addJavascript('tipsy/src/javascripts/jquery.tipsy.js', '', array ());
  $response->addJavascript('ui.formIngresoEncuestado.js', '', array ());
}
else if ($templateName.$this->viewName == 'homeSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('author', 'Gustavo Lacoste &lt;gustavo@lacosox.org&gt;, Carlos Henriquez &lt;carlos.henriquez.lara@gmail.com&gt;, Absalon Valdes O. &lt;absalon.valdes@hotmail.com&gt;', false, false);
  $response->addMeta('copyright', 'Licensed under GPL and MIT.', false, false);
  $response->addMeta('title', 'Sitema de registro de adolecentes infractores de ley', false, false);
  $response->addMeta('description', 'Proyecto FONDEF d08i1205 (ESTRATEGIA ECOSISTÉMICA ESPECIALIZADA DE INTERVENCIÓN DIFERENCIADA PARA FAVORECER LA INTEGRACIÓN PSI COSOCIAL DE ADOLESCENTES INFRACTORES DE LEY)', false, false);
  $response->addMeta('keywords', 'psicologia,psico, delitos,d08i1205,', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'all', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('text.css', '', array ());
  $response->addStylesheet('redmond/jquery-ui-1.8.1.custom.css', '', array ());
  $response->addStylesheet('960.css', '', array ());
  $response->addStylesheet('formee/css/form-structure.css', '', array ());
  $response->addStylesheet('formee/css/form-style.css', '', array ());
  $response->addStylesheet('style-dialog-calendars.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('ayuda.css', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.1.custom.min.js', '', array ());
  $response->addJavascript('jquery.history.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('jquery.validate.js', '', array ());
  $response->addJavascript('jquery.Rut.min.js', '', array ());
  $response->addJavascript('funciones_global.js', '', array ());
  $response->addJavascript('jquery.cookie.js', '', array ());
  $response->addJavascript('funciones_Ayuda.js', '', array ());
  $response->addJavascript('funciones_Timer.js', '', array ());
  $response->addJavascript('tipsy/src/javascripts/jquery.tipsy.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('ui.homeSuccess.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('author', 'Gustavo Lacoste &lt;gustavo@lacosox.org&gt;, Carlos Henriquez &lt;carlos.henriquez.lara@gmail.com&gt;, Absalon Valdes O. &lt;absalon.valdes@hotmail.com&gt;', false, false);
  $response->addMeta('copyright', 'Licensed under GPL and MIT.', false, false);
  $response->addMeta('title', 'Sitema de registro de adolecentes infractores de ley', false, false);
  $response->addMeta('description', 'Proyecto FONDEF d08i1205 (ESTRATEGIA ECOSISTÉMICA ESPECIALIZADA DE INTERVENCIÓN DIFERENCIADA PARA FAVORECER LA INTEGRACIÓN PSI COSOCIAL DE ADOLESCENTES INFRACTORES DE LEY)', false, false);
  $response->addMeta('keywords', 'psicologia,psico, delitos,d08i1205,', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'all', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('text.css', '', array ());
  $response->addStylesheet('redmond/jquery-ui-1.8.1.custom.css', '', array ());
  $response->addStylesheet('960.css', '', array ());
  $response->addStylesheet('formee/css/form-structure.css', '', array ());
  $response->addStylesheet('formee/css/form-style.css', '', array ());
  $response->addStylesheet('style-dialog-calendars.css', '', array ());
  $response->addStylesheet('base.css', '', array ());
  $response->addStylesheet('ayuda.css', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.1.custom.min.js', '', array ());
  $response->addJavascript('jquery.history.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('jquery.validate.js', '', array ());
  $response->addJavascript('jquery.Rut.min.js', '', array ());
  $response->addJavascript('funciones_global.js', '', array ());
  $response->addJavascript('jquery.cookie.js', '', array ());
  $response->addJavascript('funciones_Ayuda.js', '', array ());
  $response->addJavascript('funciones_Timer.js', '', array ());
  $response->addJavascript('tipsy/src/javascripts/jquery.tipsy.js', '', array ());
}

